name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      # Generate an RSS Feed XML file
      - name: Generate RSS Feed XML file
        run: dotnet run --project RSSFeedXMLFileGenerator -o BlazorWasmApp1/wwwroot/feed.xml

      # Publish the site
      - name: Publish
        run: dotnet publish BlazorWasmApp1 -c Release -o public -p GHPages=true -f net9.0

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/wwwroot
          force_orphan: true
